---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.padok.fr
  namespace: traefik-system
spec:
  dnsNames:
    - traefik.padok.fr
  secretName: traefik.padok.fr
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer